s---
title: "Introduction to R for data analysis"
output:
  html_document:
    toc: false
---

[Research Computing Center](https://rcc.uchicago.edu)<br>
[University of Chicago](https://www.uchicago.edu)

Date: Tuesday, August 1, 2017<br>
Time: 2:00 pm to 4:00 pm<br>
Location: Zar Room, John Crerar Library<br>
Instructor: Peter Carbonetto

## General Information

The [R computing environment](http://cran.r-project.org) has become
one of the most important tools in quantitative research, from
computational biology to financial modeling. This short workshop will
expose participants to the basic elements of R through an analysis of
[Divvy bike trip data](https://www.divvybikes.com/system-data). The
aim is to provide participants with the basic tools to explore the
features of R and RStudio on their own, either on the RCC cluster, or
on their own computer.

**Level:** Introductory

**Prerequistes:** Mac, Linux, or Windows operating system that they
have administrative privileges on. An RCC account is helpful, but not
required. No previous programming experience is required.

**Where:** Kathleen A. Zar Room, John Crerar Library, University of
Chicago ([OpenStreetMap](https://www.openstreetmap.org/search?query=john%20crerar%20library#map=18/41.79053/-87.60282)).

**Other information:** This workshop is an attempt to apply elements of
the
[Software Carpentry approach](http://software-carpentry.org/lessons).
See also
[this article](http://dx.doi.org/10.12688/f1000research.3-62.v2).
Please also take a look at the [Code of Conduct](conduct.html), and the
[license information](license.html).

## Aims

*Aims go here.*

## Outline

The purpose of this project is to gain some insight into city-wide
biking trends by analyzing the
[Divvy trip data](https://www.divvybikes.com/system-data). Also, I
examine trip data from one bike station at the University of Chicago
to compare the biking patterns at the university against city-wide
trends.

All the results and plots presented in the pages below should be
reproduceable on your computer. Follow the
[Setup Instructions](setup.html) if you are interested in reproducing
the results for yourself.

These are the results of my analyses. They were generated by rendering
the [R Markdown documents](https://github.com/pcarbo/wflow-divvy/tree/master/analysis)
into webpages.

1. [A first glance at the Divvy data.](first-glance.html)

2. [A map of the Divvy stations in Chicago.](station-map.html)

3. [Exploring daily bike commuting trends from the Divvy
data.](time-of-day-trends.html)

4. [Exploring seasonal biking trends from the Divvy
data.](seasonal-trends.html)

<br>

## Useful resources

+ [CRAN](http://cran.r-project.org).

+ [RStudio](http://rstudio.com).

+ [Using R with conda](https://conda.io/docs/r-with-conda.html).

+ [Jupyter](https://jupyter.org) (included with Anaconda).

+ [BioConductor](http://bioconductor.org).

+ [Software Carpentry](http://software-carpentry.org/lessons).

+ [Data Carpentry](http://www.datacarpentry.org/lessons).

+ [R for Data Science](http://r4ds.had.co.nz).

+ [Some advanced topics in R](http://adv-r.had.co.nz).

+ [Short guide to writing your own R package](http://r-pkgs.had.co.nz).

+ [Introductory Statistics with R](http://staff.pubhealth.ku.dk/~pd/ISwR.html)
(available through [University of Chicago
library](https://www.lib.uchicago.edu)).

+ [Data Analysis for the Life
Sciences](https://leanpub.com/dataanalysisforthelifesciences).

+ [STAT Labs: Mathematical Statistics through
Applications](https://www.stat.berkeley.edu/~statlabs).

## Credits

These materials were developed by [Peter
Carbonetto](http://pcarbo.github.io) at the [University of
Chicago](https://www.uchicago.edu).

Thanks to [John Blischak](https://github.com/jdblischak) and
[Matthew Stephens](http://stephenslab.uchicago.edu) for their assistance and
support. Also, thanks to [Larry
Layne](https://rstudio-pubs-static.s3.amazonaws.com/63061_90f5136ffdf74740b6ba4ad8f2fd72fe.html)
and [Austin
Wehrwein](http://www.austinwehrwein.com/data-visualization/heatmaps-with-divvy-data)
for sharing their analyses of the Divvy trip data that inspired some
of the investigations here.
